---
title: "Titanic 3"
output: html_notebook
---

# Load the data and libraries
```{r, message = FALSE}
install.packages('mice')
library('mice')
library('randomForest')
library("rpart")
train <- read.csv('./input/train.csv', stringsAsFactors = F, na.strings="")
test  <- read.csv('./input/test.csv', stringsAsFactors = F, na.strings="")
```
# Functions
### Add Title feature from name
```{r}
addTitle <- function(data) {
  data$Title <- gsub('(.*, )|(\\..*)', '', data$Name)
  
  rare_titles <- c('Dona', 'Lady', 'the Countess','Capt', 'Col', 'Don', 'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer')
  
  data$Title[data$Title == 'Mlle']        <- 'Miss'
  data$Title[data$Title == 'Ms']          <- 'Miss'
  data$Title[data$Title == 'Mme']         <- 'Mrs' 
  data$Title[data$Title %in% rare_titles]  <- 'Rare Title'
  data$Embarked[is.na(data$Embarked)] <- "S"
  return(data)
}
```
### Fix missing embarked in training set
```{r}
embarked <- function(data) {
  data$Embarked[c(62, 830)] <- 'C'
  return(data)
}
```
### Add surname
```{r}
addSurname <- function(data) {
  data$Surname <- sapply(data$Name,  
                      function(x) strsplit(x, split = '[,.]')[[1]][1])
  return(data)
}
```
### Add family size
```{r}
addFamilySize <- function(data) {
  data$Fsize <- data$SibSp + data$Parch + 1
  
    # Discretize family size
  data$FsizeD[data$Fsize == 1] <- 'singleton'
  data$FsizeD[data$Fsize < 5 & data$Fsize > 1] <- 'small'
  data$FsizeD[data$Fsize > 4] <- 'large'

  return(data)
}
```
### factorize
```{r}
factorize <- function(data) {
  factor_vars <- c('PassengerId','Pclass','Sex','Embarked',
                 'Title','Surname','FsizeD')

  data[factor_vars] <- lapply(data[factor_vars], function(x) as.factor(x))
  return(data)
}
```
### Impute Age
```{r}
impAge <- function(data) {
  bad_cols <- c('PassengerId','Name','Ticket','Cabin','Family','Surname','Survived')
  mice_mod <- mice(data[, !names(data) %in% bad_cols], method='rf') 
  mice_output <- complete(mice_mod)
  data$Age <- mice_output$Age
  return(data)
}
```
# Training
### Apply functions
```{r}
nTrain = addTitle(train)
nTrain = embarked(nTrain)
nTrain = addSurname(nTrain)
nTrain = addFamilySize(nTrain)
nTrain = factorize(nTrain)
nTrain = impAge(nTrain)
```
### Build decision tree
```{r}
treeFit <- rpart(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked + Title + FsizeD,
               data=nTrain, 
               method="class")
```
### Predict decision tree fit
```{r}
treePrediction <- predict(treeFit, nTest, type = "class")
treePrediction
solution <- data.frame(PassengerID = nTest$PassengerId, Survived = treePrediction)
write.csv(solution, file = 'rpart_tree_mod_Solution_1.csv', row.names = F)
```

### Build random forest model
```{r}
set.seed(333)
rf_model <- randomForest(factor(Survived) ~ Pclass + Sex + Age + SibSp + Parch + 
                                            Fare + Embarked + Title + 
                                            FsizeD,
                                            data = nTrain)
plot(rf_model)
```
# Evaluate Model
```{r}
importance <- importance(rf_model)

varImportance <- data.frame(Variables = row.names(importance), 
                            Importance = round(importance[ ,'MeanDecreaseGini'],2))

rankImportance <- varImportance %>%
  mutate(Rank = paste0('#',dense_rank(desc(Importance))))
rankImportance
```
# Predict
```{r}
nTest = addTitle(test)
nTest = addSurname(nTest)
nTest = addFamilySize(nTest)
nTest = factorize(nTest)
nTest = impAge(nTest)

prediction <- predict(rf_model, nTest, type = "response")

length(nTest$PassengerId)
length(prediction)
passID <- as.vector(nTest$PassengerId)
pred <- as.vector(prediction)
solution <- data.frame(PassengerID = passID, Survived = pred)
solution
colSums()
which(is.na(pred))
pred[153] <- 0
# Write the solution to file
write.csv(solution, file = 'rf_mod_Solution_1.csv', row.names = F)
```








